[repository]
name = "hyprfocus"
authors = ["VortexCoyote, OakleyCord, vaxerski, DRAGONTOS"]

[hyprfocus]
description = "a focus animation plugin for Hyprland inspired by Flashfocus"
authors = ["VortexCoyote, OakleyCord, vaxerski, DRAGONTOS"]
output = "hyprfocus.so"
build = [
    "make all"
]
